### PR TITLE
Make message updates generic

### PR DESCRIPTION
**Pull request by wojpawlik**
Supersedes https://github.com/telegraf/telegraf/pull/1691.

### CODE REVIEW

**Comment by KnorpelSenf** [comment]
Why only for messages and nothing else? This is inconsistent.

**Comment by MKRhere** [comment]
> and nothing else

Which other update type needs it?

**Comment by KnorpelSenf** [comment]
Callback query updates are also unions. So but it was your intention to apply this pattern to the complete API?

**Comment by wojpawlik** [comment]
They aren't _actual_ unions. Changing them to match would be breaking, and is thus out of scope.

**Comment by KnorpelSenf** [comment]
Damn it, I missed that typegram is wrong in that respect, as they're actually unions and they should be represented as such. I did this correctly for grammY.

But well, if that's not supposed to be corrected anyway, then we can just continue building on top of the current state.

**Review by KnorpelSenf — APPROVED** [review]
Seems to do what it's supposed to do, will merge after @MKRhere confirms that this is good

**Comment by MKRhere** [comment]
LGTM

**Pull request merged**
